name: Website Release

on:
  release:
    types: [published]

jobs:
  export:
    name: 🎉 Release
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 20.11.1
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1'

    - name: Export Project
      run: |
        npm install
        NODE_ENV=production BASE_PATH='' npm run build

    - name: List output files
      run: ls

    - name: Reset repo to fix build changes
      run: git reset --hard

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      if: success()
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.PROD_USER }}
        password: ${{ secrets.PROD_PASS }}
        local-dir: out/ # This folder is NOT going to upload by default unless you add it to .git-ftp-include
        server-dir: ./
